DROP TABLE IF EXISTS Images;
DROP TABLE IF EXISTS Tags;

CREATE TABLE Images (
id INTEGER PRIMARY KEY AUTOINCREMENT,
filePath TEXT,
uploadDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Tags (
tag TEXT,
idImage INTEGER,
PRIMARY KEY(tag, idImage)
FOREIGN KEY(idImage) REFERENCES Images(id)
);
